import dotenv from "dotenv";

dotenv.config({
    path: "./.env",
});

const CONFIG = { ...process.env };

CONFIG.PORT = CONFIG.PORT || 8000;
CONFIG.DB_NAME = "projekt-x-db";
CONFIG.CORS_ORIGIN = JSON.parse(CONFIG.CORS_ORIGIN || "");

// CONFIG.MONGODB_URL = process.env.MONGODB_URL;
// CONFIG.ACCESS_TOKEN_EXPIRY = process.env.ACCESS_TOKEN_EXPIRY;
// CONFIG.ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET;
// CONFIG.REFRESH_TOKEN_EXPIRY = process.env.REFRESH_TOKEN_EXPIRY;
// CONFIG.REFRESH_TOKEN_SECRET = process.env.REFRESH_TOKEN_SECRET;
// CONFIG.CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY;
// CONFIG.CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET;
// CONFIG.CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME;

export default CONFIG;
